[package]
name = "ssi-vc"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Verifiable Claims for the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-claims/"

[features]
# Default features.
default = ["w3c", "dif", "ed25519", "rsa", "secp256k1", "secp256r1", "tezos", "eip712", "aleo", "solana"]

# Enables signature suites specified by the W3C.
w3c = ["ssi-vc-data-integrity/w3c"]

# Enables signature suites specified by DIF.
dif = ["ssi-vc-data-integrity/dif"]

# Enables signature suites based on ED25519:
# - `Ed25519Signature2018`
# - `Ed25519Signature2020`
# - `EdDsa2022`
ed25519 = ["ssi-vc-data-integrity/ed25519", "ssi-verification-methods/ed25519"]

# Enables signature suites based on secp256k1:
# - `EcdsaSecp256k1Signature2019`
secp256k1 = ["ssi-vc-data-integrity/secp256k1", "ssi-verification-methods/secp256k1"]

# Enables signature suites based on secp256r1:
# - `EcdsaSecp256r1Signature2019`
secp256r1 = ["ssi-vc-data-integrity/secp256r1", "ssi-verification-methods/secp256r1"]

# Enables `RsaSignature2018`
rsa = ["ssi-vc-data-integrity/rsa", "ssi-verification-methods/rsa"]

# Enables all the tezos signatures suites:
# - `Ed25519BLAKE2BDigestSize20Base58CheckEncodedSignature2021`
# - `P256BLAKE2BDigestSize20Base58CheckEncodedSignature2021`
# - `TezosJcsSignature2021`
# - `TezosSignature2021`
tezos = ["ssi-vc-data-integrity/tezos"]

# Enables `AleoSignature2021`
aleo = ["ssi-jwk/aleo", "ssi-vc-data-integrity/aleo", "ssi-verification-methods/aleo"]

# Enables `Eip712Signature2021`
eip712 = ["ssi-eip712", "ssi-vc-data-integrity/eip712"]

# Enables `SolanaSignature2021`
solana = ["ssi-vc-data-integrity/solana", "ssi-verification-methods/solana"]

# Enables `EthereumPersonalSignature2021`
ethereum = []

[dependencies]
ssi-core.workspace = true
ssi-security.workspace = true
ssi-jwk.workspace = true
ssi-jws.workspace = true
ssi-crypto.workspace = true
ssi-verification-methods.workspace = true
ssi-claims-core.workspace = true
ssi-vc-core.workspace = true
ssi-vc-data-integrity.workspace = true
ssi-rdf.workspace = true
ssi-json-ld.workspace = true
json-syntax.workspace = true
json-ld.workspace = true
iref.workspace = true
rdf-types.workspace = true
xsd-types.workspace = true
linked-data.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

pin-project.workspace = true

ssi-eip712 = { workspace = true, optional = true }