[package]
name = "ssi-did-test"
version = "0.3.0"
authors = ["Spruce Systems, Inc."]
edition = "2021"
license = "Apache-2.0"
description = "did-test-suite test vector generator"
publish = false

[dependencies]
# did-webkey.workspace = true
# did-onion.workspace = true
async-std = { version = "1.9", features = ["attributes"] }