[package]
name = "ssi-vc-data-integrity"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Verifiable Credentials Data Model v1.1 for the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-claims/"

[features]
# Default features.
default = ["w3c", "ed25519", "rsa", "secp256k1", "secp256r1", "tezos", "eip712", "aleo", "solana"]

# Enables signature suites specified by the W3C.
w3c = ["ssi-vc-data-integrity-suites/w3c"]

# Enables signature suites specified by the Decentralized Identify Foundation (DIF).
dif = ["ssi-vc-data-integrity-suites/dif"]

# Enables signature suites based on ED25519:
# - `Ed25519Signature2018`
# - `Ed25519Signature2020`
# - `EdDsa2022`
ed25519 = ["ssi-vc-data-integrity-suites/ed25519"]

# Enables signature suites based on secp256k1:
# - `EcdsaSecp256k1Signature2019`
secp256k1 = ["ssi-vc-data-integrity-suites/secp256k1"]

# Enables signature suites based on secp256r1:
# - `EcdsaSecp256r1Signature2019`
secp256r1 = ["ssi-vc-data-integrity-suites/secp256r1"]

# Enables `RsaSignature2018`
rsa = ["ssi-vc-data-integrity-suites/rsa"]

# Enables all the tezos signatures suites:
# - `Ed25519BLAKE2BDigestSize20Base58CheckEncodedSignature2021`
# - `P256BLAKE2BDigestSize20Base58CheckEncodedSignature2021`
# - `TezosJcsSignature2021`
# - `TezosSignature2021`
tezos = ["ssi-vc-data-integrity-suites/tezos"]

# Enables `AleoSignature2021`
aleo = ["ssi-vc-data-integrity-suites/aleo"]

# Enables `Eip712Signature2021`
eip712 = ["ssi-vc-data-integrity-suites/eip712"]

# Enables `SolanaSignature2021`
solana = ["ssi-vc-data-integrity-suites/solana"]

# Enables `EthereumPersonalSignature2021`
ethereum = ["ssi-vc-data-integrity-suites/ethereum"]

[dependencies]
ssi-vc-data-integrity-core.workspace = true
ssi-vc-data-integrity-suites.workspace = true
ssi-vc-core.workspace = true
ssi-core.workspace = true
ssi-security.workspace = true
ssi-crypto.workspace = true
ssi-jws.workspace = true
ssi-jwk.workspace = true
ssi-rdf.workspace = true
ssi-json-ld.workspace = true
ssi-verification-methods.workspace = true
ssi-eip712.workspace = true
ssi-claims-core.workspace = true
iref.workspace = true
rdf-types.workspace = true
json-ld.workspace = true
linked-data.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
async-std = { version = "1.9", features = ["attributes"] }
# treeldr-rust-macros.workspace = true
static-iref.workspace = true
rand = "0.7"
hashbrown = "0.13.0"
iref = { workspace = true, features = ["hashbrown"] }
xsd-types.workspace = true
chrono.workspace = true
serde = { workspace = true, features = ["derive"] }