[package]
name = "ssi-zcap-ld"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
thiserror = "1.0"
ssi-jwk = { path = "../ssi-jwk", version = "0.1", default-features = false }
ssi-core = { path = "../ssi-core", version = "0.1" }
ssi-dids = { path = "../ssi-dids", version = "0.1" }
ssi-json-ld = { path = "../ssi-json-ld", version = "0.1", default-features = false }
ssi-ldp = { path = "../ssi-ldp", version = "0.1", default-features = false }

[dev-dependencies]
async-std = { version = "1.9", features = ["attributes"] }
ssi-ldp = { path = "../ssi-ldp", version = "0.1", default-features = false, features = ["ed25519"] }
