[package]
name = "ssi-zcap-ld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["eip", "w3c"]
w3c = ["secp256k1", "secp256r1", "rsa", "ed25519", "ssi-ldp/w3c"]
secp256k1 = ["ssi-ldp/secp256k1"]
secp256r1 = ["ssi-ldp/secp256r1"]
ed25519 = ["ssi-ldp/ed25519"]
rsa = ["ssi-ldp/rsa"]
eip = ["ssi-ldp/eip"]
tezos = ["ssi-ldp/tezos"]
solana = ["ssi-ldp/solana"]
aleo = ["ssi-ldp/aleo"]

openssl = ["ssi-ldp/openssl", "ssi-jwk/openssl"]
ring = ["ssi-ldp/ring", "ssi-jwk/ring"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
thiserror = "1.0"
ssi-jwk = { path = "../ssi-jwk", version = "0.1" }
ssi-core = { path = "../ssi-core", version = "0.1" }
ssi-dids = { path = "../ssi-dids", version = "0.1" }
ssi-json-ld = { path = "../ssi-json-ld", version = "0.1" }
ssi-ldp = { path = "../ssi-ldp", version = "0.1" }

[dev-dependencies]
async-std = { version = "1.9", features = ["attributes"] }
