[package]
name = "ssi-zcap-ld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
thiserror = "1.0"
ssi-jwk = { path = "../ssi-jwk", version = "0.1" }
ssi-core = { path = "../ssi-core", version = "0.1" }
ssi-dids = { path = "../ssi-dids", version = "0.1" }
ssi-json-ld = { path = "../ssi-json-ld", version = "0.1" }
ssi-ldp = { path = "../ssi-ldp", version = "0.1" }
