[package]
name = "ssi-ssh"
version = "0.2.1"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Implementation of SSH related functionalities for the ssi library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-ssh/"

[features]
default = ["secp256r1"]
secp256r1 = ["ssi-jwk/secp256r1"]

[dependencies]
thiserror = "1.0"
ssi-jwk = { workspace = true, default-features = false }
sshkeys = "0.3"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
