[package]
name = "ssi-claims-core"
version = "0.2.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Core types and traits for Verifiable Claims in the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-claims/"

[dependencies]
ssi-crypto.workspace = true
thiserror.workspace = true
chrono.workspace = true
ssi-json-ld.workspace = true
ssi-eip712.workspace = true
