[package]
name = "ssi-token-status-list"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "EITF Token Status List implementation for the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-token-status-list/"

[dependencies]
ssi-jwt.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
iref.workspace = true
base64.workspace = true