[package]
name = "ssi-data-integrity-core"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Verifiable Credential Data Integrity 1.0 implementation for the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-data-integrity/"

[dependencies]
ssi-verification-methods.workspace = true
# async-trait.workspace = true
rdf-types.workspace = true
xsd-types = { workspace = true, features = ["serde"] }
# treeldr-rust-prelude.workspace = true
linked-data = { workspace = true, features = ["derive"] }
ssi-core.workspace = true
ssi-crypto.workspace = true
ssi-jwk.workspace = true
ssi-jws.workspace = true
ssi-rdf.workspace = true
ssi-json-ld.workspace = true
ssi-claims-core.workspace = true
ssi-security.workspace = true
# ssi-tzkey = { workspace = true, optional = true }
# ssi-eip712 = { workspace = true, optional = true }
# ssi-caips.workspace = true
chrono.workspace = true
# multibase.workspace = true
iref.workspace = true
thiserror.workspace = true
static-iref.workspace = true
json-ld = { workspace = true, features = ["serde"] }
locspan.workspace = true
grdf.workspace = true
hex.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
json-syntax.workspace = true
derivative.workspace = true
educe.workspace = true
futures.workspace = true
self_cell = "1.0.1"
contextual.workspace = true

# bs58 = { workspace = true, optional = true }

# ed25519-dalek = { version = "1", optional = true }
# k256 = { version = "0.11", optional = true, features = ["ecdsa", "sha256"] }
# p256 = { version = "0.11", optional = true, features = ["ecdsa"] }
# p384 = { version = "0.11", optional = true, features = ["ecdsa"] }
# sha2 = { version = "0.10", optional = true }

# # only needed by non LD suites.
# serde_json = { workspace = true, optional = true }
# serde_jcs = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
