[package]
name = "ssi-tzkey"
version = "0.1.1"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Implementation of Tezos related functions for the ssi library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-tzkey/"

[dependencies]
ssi-jwk = { path = "../ssi-jwk", version = "0.1", default-features = false, features = [
  "tezos",
] }
ssi-jws = { path = "../ssi-jws", version = "0.1", default-features = false, features = [
  "tezos",
] }
ed25519-dalek = "2.0.0"
thiserror = "1.0"
bs58 = { version = "0.4", features = ["check"] }

[dev-dependencies]
serde_json = "1.0"
hex = "0.4"
