[package]
name = "ssi-tzkey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssi-jwk = { path = "../ssi-jwk" }
ssi-jws = { path = "../ssi-jws" }
thiserror = "1.0"
bs58 = { version = "0.4", features = ["check"] }

[dev-dependencies]
serde_json = "1.0"
hex = "0.4"
