[package]
name = "ssi-tzkey"
version = "0.1.0"
edition = "2021"

[dependencies]
ssi-jwk = { path = "../ssi-jwk", version = "0.1", default-features = false, features = ["tezos"]}
ssi-jws = { path = "../ssi-jws", version = "0.1", default-features = false, features = ["tezos"] }
ed25519-dalek = "1.0.1"
thiserror = "1.0"
bs58 = { version = "0.4", features = ["check"] }

[dev-dependencies]
serde_json = "1.0"
hex = "0.4"
