[package]
name = "ssi-contexts"
version = "0.1.7"
authors = ["Spruce Systems, Inc."]
edition = "2021"
license = "Apache-2.0"
description = "JSON-LD context files related to Verifiable Credentials, Decentralized Identifiers, and Linked Data Proofs"
repository = "https://github.com/spruceid/ssi/"
homepage = "https://github.com/spruceid/ssi/tree/main/contexts/"
documentation = "https://docs.rs/ssi-contexts/"
