[package]
name = "did-ion"
version = "0.3.1"
authors = ["Spruce Systems, Inc."]
edition = "2021"
license = "Apache-2.0"
keywords = ["ssi", "did"]
categories = ["web-programming::http-client"]
description = "did:ion DID method implementation, using the ssi crate and ION/Sidetree REST API"
repository = "https://github.com/spruceid/ssi/"
homepage = "https://github.com/spruceid/ssi/tree/main/did-ion/"
documentation = "https://docs.rs/did-ion/"

[features]
native-tls = ["reqwest/native-tls"]
rustls = ["reqwest/rustls-tls"]

[dependencies]
ssi-verification-methods.workspace = true
ssi-dids-core = { workspace = true, features = ["http"] }
ssi-jwk = { workspace = true, features = ["secp256k1"] }
ssi-jws.workspace = true
ssi-jwt.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_jcs.workspace = true
iref.workspace = true
thiserror.workspace = true

base64.workspace = true
sha2 = "0.10"
json-patch.workspace = true
reqwest.workspace = true

[target.'cfg(target_os = "android")'.dependencies.reqwest]
workspace = true
features = ["native-tls-vendored"]

[dev-dependencies]
lazy_static = "1.4"
ssi-jws = { workspace = true, features = ["secp256k1"] }
