name: ssi
description: A new flutter plugin project.
version: 0.0.1
author: Charles E. Lehner <charles.lehner@spruceid.com>
homepage: https://github.com/spruceid/ssi/tree/main/flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.spruceid.ssi
        pluginClass: SsiFlutterPlugin
      ios:
        pluginClass: SsiFlutterPlugin
