[package]
name = "did-method-key"
version = "0.2.2"
authors = ["Spruce Systems, Inc."]
edition = "2021"
license = "Apache-2.0"
keywords = ["ssi", "did"]
categories = ["cryptography::cryptocurrencies"]
description = "did:key DID method, using the ssi crate"
repository = "https://github.com/spruceid/ssi/"
homepage = "https://github.com/spruceid/ssi/tree/main/did-key/"
documentation = "https://docs.rs/did-key/"

[features]
default = ["secp256k1", "secp256r1"]
secp256k1 = [
	"k256",
	"ssi-jwk/secp256k1"
]
secp256r1 = [
	"p256",
	"ssi-jwk/secp256r1"
]
secp384r1 = ["ssi-jwk/secp384r1"]

[dependencies]
ssi-dids-core.workspace = true
ssi-jwk.workspace = true
ssi-multicodec.workspace = true
bs58 = { version = "0.4", features = ["check"] }
multibase.workspace = true
iref.workspace = true
static-iref.workspace = true
thiserror.workspace = true
serde_json.workspace = true
simple_asn1 = "^0.5.2"
k256 = { version = "0.13.1", optional = true, features = ["ecdsa"] }
p256 = { version = "0.13.2", optional = true, features = ["ecdsa"] }

[dev-dependencies]
ssi-claims.workspace = true
ssi-vc-data-integrity.workspace = true
xsd-types.workspace = true
linked-data.workspace = true
serde = { workspace = true, features = ["derive"] }
async-std = { version = "1.9", features = ["attributes"] }
rand_chacha.workspace = true
rand_chacha_old = { package = "rand_chacha", version = "0.2" }