[package]
name = "ssi-eip712"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Ethereum's typed structured data hashing and signing (EIP-712)"
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-eip712/"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_jcs = "0.1"
thiserror.workspace = true
ssi-crypto.workspace = true
keccak-hash = "0.7"
hex = "0.4"
rdf-types.workspace = true
indexmap = { version = "2.0.0", features = ["serde"] }

[dev-dependencies]
lazy_static = "1.4"