[package]
name = "ssi-data-integrity"
version = "0.1.1"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Verifiable Credentials Data Model v1.1 for the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-claims/"

[features]
default = ["w3c", "ed25519", "rsa", "secp256k1", "secp256r1"]

## Signature suites specified by the W3C.
##
## This includes:
##   - `JsonWebSignature2020`
##   - `RsaSignature2018` (requires `rsa`)
##   - `Ed25519Signature2018` (requires `ed25519`)
##   - `Ed25519Signature2020` (requires `ed25519`)
##   - `EdDsa2022` (requires `ed25519`)
##   - `EcdsaSecp256k1Signature2019` (requires `secp256k1`)
##   - `EcdsaSecp256r1Signature2019` (requires `secp256r1`)
##   - `EthereumEip712Signature2021` (requires `eip712`)
w3c = ["ssi-data-integrity-suites/w3c"]

## Signature suites specified by the Decentralized Identify Foundation (DIF).
##
## This includes:
##   - `EcdsaSecp256k1RecoverySignature2020` (requires `secp256k1`)
dif = ["ssi-data-integrity-suites/dif"]

## Signature suites based on ED25519.
##
## This includes:
##   - `Ed25519Signature2018` (requires `w3c`)
##   - `Ed25519Signature2020` (requires `w3c`)
##   - `EdDsa2022` (requires `w3c`)
ed25519 = ["ssi-data-integrity-suites/ed25519"]

## Signature suites based on secp256k1.
##
## This includes:
##   - `EcdsaSecp256k1Signature2019` (requires `w3c`)
##   - `EcdsaSecp256k1RecoverySignature2020` (requires `dif`)
secp256k1 = ["ssi-data-integrity-suites/secp256k1"]

## Signature suites based on secp256r1.
##
## This includes:
##   - `EcdsaSecp256r1Signature2019` (requires `w3c`)
##   - `EcdsaRdfc2019` (requires `w3c`)
secp256r1 = ["ssi-data-integrity-suites/secp256r1"]

## Signature suites based on secp384r1.
##
## This includes:
##   - `EcdsaRdfc2019` (requires `w3c`)
secp384r1 = ["ssi-data-integrity-suites/secp384r1"]

## Signature suites based on RSA.
##
## This includes:
##   - `RsaSignature2018` (requires `w3c`)
rsa = ["ssi-data-integrity-suites/rsa"]

## Tezos signatures suites.
##
## This includes:
##   - `TezosJcsSignature2021`
##   - `TezosSignature2021`
##   - `Ed25519BLAKE2BDigestSize20Base58CheckEncodedSignature2021` (requires `ed25519`)
##   - `P256BLAKE2BDigestSize20Base58CheckEncodedSignature2021` (requires `secp256r1`)
tezos = ["ssi-data-integrity-suites/tezos"]

## Enables `AleoSignature2021`.
aleo = ["ssi-data-integrity-suites/aleo"]

## Signature suites based on Ethereum EIP-712.
## 
## This includes:
##   - `Eip712Signature2021` (requires `ethereum`).
##   - `EthereumEip712Signature2021` (requires `w3c`)
eip712 = ["ssi-data-integrity-suites/eip712"]

# Enables `SolanaSignature2021`
solana = ["ssi-data-integrity-suites/solana"]

## Ethereum signature suites.
##
## This includes:
##   - `EthereumPersonalSignature2021`
##   - `Eip712Signature2021` (requires `eip712`)
ethereum = ["ssi-data-integrity-suites/ethereum"]

## BBS cryptographic suites.
bbs = ["ssi-bbs", "ssi-data-integrity-suites/bbs"]

[dependencies]
ssi-data-integrity-core.workspace = true
ssi-data-integrity-suites.workspace = true
ssi-core.workspace = true
ssi-security.workspace = true
ssi-crypto.workspace = true
ssi-jws.workspace = true
ssi-jwk.workspace = true
ssi-rdf.workspace = true
ssi-json-ld.workspace = true
ssi-verification-methods.workspace = true
ssi-eip712.workspace = true
ssi-claims-core.workspace = true
ssi-di-sd-primitives.workspace = true
ssi-bbs = { workspace = true, optional = true }
iref.workspace = true
rdf-types.workspace = true
linked-data.workspace = true
serde.workspace = true
serde_json.workspace = true
json-syntax.workspace = true
thiserror.workspace = true
chrono.workspace = true

[dev-dependencies]
ssi-multicodec.workspace = true
serde = { workspace = true, features = ["derive"] }
async-std = { workspace = true, features = ["attributes"] }
