[package]
name = "ssi-crypto"
version = "0.1.0"
edition = "2021"

[features]
default = ["ring"]
secp256k1 = ["k256", "k256/keccak256", "keccak-hash"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
sha2 = { version = "0.10", optional = true }
ring = { version = "0.16", optional = true }
k256 = { version = "0.9.6", optional = true, features = ["zeroize", "ecdsa"] }
keccak-hash = { version = "0.7", optional = true }
p256 = { version = "0.9.0", optional = true, features = ["zeroize", "ecdsa"] }
ed25519-dalek = { version = "1", optional = true }
