[package]
name = "ssi-di-sd-primitives"
version = "0.2.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Selective Disclosure primitive for Data-Integrity suites"
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-di-sd-primitives/"

[dependencies]
ssi-core.workspace = true
ssi-rdf.workspace = true
ssi-json-ld.workspace = true
linked-data.workspace = true
iref.workspace = true
hmac = { version = "0.12.1", features = ["reset"] }
sha2.workspace = true
rdf-types.workspace = true
base64.workspace = true
digest.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
uuid = { workspace = true, features = ["v4"] }
getrandom.workspace = true
hex.workspace = true

[dev-dependencies]
async-std = { workspace = true, features = ["attributes"] }
lazy_static.workspace = true
json-syntax.workspace = true
