[package]
name = "ssi-dids"
version = "0.2.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "DID methods of the ssi library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-dids/"

[features]
default = ["http"]
example = ["ssi-dids-core/example"]
http = ["ssi-dids-core/http"]

[dependencies]
ssi-dids-core.workspace = true
did-ethr.workspace = true
did-ion.workspace = true
did-jwk.workspace = true
did-method-key.workspace = true
did-pkh.workspace = true
did-tz.workspace = true
did-web.workspace = true