use std::collections::BTreeMap;

use super::value_or_array;
use crate::CryptographicSuite;
use educe::Educe;
use serde::Serialize;
use ssi_verification_methods::{CowVerificationMethod, ProofPurpose};

/// Data Integrity Proof.
///
/// A data integrity proof provides information about the proof mechanism,
/// parameters required to verify that proof, and the proof value itself.
#[derive(Educe, Serialize)]
#[serde(bound(serialize = "S: CryptographicSuite"))]
#[educe(Debug(bound("S: std::fmt::Debug")))]
#[educe(Clone(bound("S: Clone")))]
#[serde(rename_all = "camelCase")]
pub struct ProofRef<'a, S> {
    /// Proof context.
    #[serde(rename = "@context", default, skip_serializing_if = "Option::is_none")]
    pub context: Option<&'a ssi_json_ld::syntax::Context>,

    #[serde(flatten, with = "cryptosuite_type_ref")]
    pub r#type: &'a S,

    /// Date a creation of the proof.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created: Option<xsd_types::DateTimeStamp>,

    /// Verification method.
    pub verification_method: &'a CowVerificationMethod,

    /// Purpose of the proof.
    pub proof_purpose: ProofPurpose,

    /// Specifies when the proof expires.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires: Option<xsd_types::DateTimeStamp>,

    #[allow(rustdoc::bare_urls)]
    /// Conveys one or more security domains in which the proof is meant to be
    /// used.
    ///
    /// A verifier SHOULD use the value to ensure that the proof was intended to
    /// be used in the security domain in which the verifier is operating. The
    /// specification of the domain parameter is useful in challenge-response
    /// protocols where the verifier is operating from within a security domain
    /// known to the creator of the proof.
    ///
    /// Example domain values include: `domain.example`` (DNS domain),
    /// `https://domain.example:8443` (Web origin), `mycorp-intranet` (bespoke
    /// text string), and `b31d37d4-dd59-47d3-9dd8-c973da43b63a` (UUID).
    #[serde(
        with = "value_or_array",
        skip_serializing_if = "<[String]>::is_empty",
        rename = "domain"
    )]
    pub domains: &'a [String],

    /// Used to mitigate replay attacks.
    ///
    /// Used once for a particular domain and window of time. Examples of a
    /// challenge value include: `1235abcd6789`,
    /// `79d34551-ae81-44ae-823b-6dadbab9ebd4`, and `ruby`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub challenge: Option<&'a str>,

    /// Arbitrary string supplied by the proof creator.
    ///
    /// One use of this field is to increase privacy by decreasing linkability
    /// that is the result of deterministically generated signatures.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nonce: Option<&'a str>,

    /// Proof value.
    ///
    /// A string value that expresses base-encoded binary data necessary to
    /// verify the digital proof using the specified `verification_method`. The
    /// value *must* use a header and encoding as described in Section 2.4
    /// Multibase of the Controlled Identifiers v1.0 specification to express
    /// the binary data.
    ///
    /// The contents of this value are determined by a specific cryptosuite and
    /// set to the proof value generated by the Add Proof Algorithm for that
    /// cryptosuite. Alternative properties with different encodings specified
    /// by the cryptosuite *may* be used, instead of this property, to encode
    /// the data necessary to verify the digital proof.
    pub proof_value: Option<&'a str>,

    /// Extra properties unrelated to the cryptographic suite.
    #[serde(flatten)]
    pub properties: &'a BTreeMap<String, json_syntax::Value>,
}

pub mod cryptosuite_type_ref {
    use crate::CryptographicSuite;

    pub fn serialize<T: CryptographicSuite, S>(value: &&T, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        todo!()
    }
}
