[package]
name = "did-tdw"
version = "0.0.1"
authors = ["Spruce Systems, Inc."]
edition = "2021"
license = "Apache-2.0"
keywords = ["ssi", "did"]
categories = [""]
description = "did:tdw DID method, using the ssi crate"
repository = "https://github.com/spruceid/ssi/"
homepage = "https://github.com/spruceid/ssi/tree/main/did-tdw/"
documentation = "https://docs.rs/did-tdw/"
