[package]
name = "ssi-ucan"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "1.14", features = ["base64"]}
base64 = "0.12"
ssi-jwk = { path = "../ssi-jwk", version = "0.1", default-features = false }
ssi-jws = { path = "../ssi-jws", version = "0.1", default-features = false }
ssi-jwt = { path = "../ssi-jwt", version = "0.1", default-features = false }
ssi-dids = { path = "../ssi-dids", version = "0.1" }
ssi-core = { path = "../ssi-core", version = "0.1" }
ssi-caips = { path = "../ssi-caips", version = "0.1", default-features = false  }
libipld = { version = "0.13", features = ["serde-codec"] }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = { version = "0.4", features = ["serde"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", features = ["serde", "wasmbind"] }

[dev-dependencies]
async-std = { version = "1.9", features = ["attributes"] }
did-method-key = { path = "../did-key" }
ssi-jws = { path = "../ssi-jws", version = "0.1", default-features = false, features = ["ed25519"] }
