[package]
name = "ssi-vc-core"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Verifiable Credentials Data Model v1.1 for the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-claims/"

[dependencies]
iref.workspace = true
static-iref.workspace = true
chrono.workspace = true
serde = { workspace = true, features = ["derive"] }