[package]
name = "ssi-crypto"
version = "0.2.1"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Implementation of various hashes and signatures for the ssi library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-crypto/"

[features]
default = ["secp256k1", "secp256r1", "ripemd-160"]
ed25519 = ["ed25519-dalek"]
secp256k1 = ["k256", "getrandom", "keccak"]
secp256r1 = ["p256"]
secp384r1 = ["p384"]
bbs = ["dep:bbs", "pairing-plus", "rand_old", "getrandom", "sha2_old", "hkdf"]
ripemd-160 = ["ripemd160", "secp256k1"]
keccak = ["keccak-hash"]
ring = ["dep:ring"]

[dependencies]
thiserror.workspace = true
sha2 = { workspace = true }
ring = { version = "0.16", optional = true }
k256 = { workspace = true, optional = true, features = ["ecdsa"] }
p256 = { workspace = true, optional = true, features = ["ecdsa"] }
p384 = { workspace = true, optional = true, features = ["ecdsa"] }
hkdf = { version = "0.8", optional = true }
rand.workspace = true
rand_old = { package = "rand", version = "0.7", optional = true }
getrandom = { workspace = true, optional = true } # Required for wasm targets.
sha2_old = { package = "sha2", version = "0.8", optional = true }
keccak-hash = { version = "0.7", optional = true }
ed25519-dalek = { workspace = true, optional = true, features = ["rand_core"] }
ripemd160 = { version = "0.9", optional = true }
bbs = { version = "=0.4.1", optional = true }
pairing-plus = { version = "=0.19.0", optional = true }
serde = { workspace = true, features = ["derive"] }
zeroize = { version = "1.5", features = ["zeroize_derive"] }
bs58 = { workspace = true, features = ["check"] }
digest = "0.9"
iref.workspace = true
static-iref.workspace = true
async-trait.workspace = true
pin-project.workspace = true
hex.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["js"], optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
