[package]
name = "ssi-status"
version = "0.3.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Status Lists implementations for the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-token-status-list/"

[dependencies]
ssi-claims-core.workspace = true
ssi-jwk.workspace = true
ssi-jwt.workspace = true
ssi-jws.workspace = true
ssi-vc.workspace = true
ssi-verification-methods.workspace = true
ssi-data-integrity.workspace = true
ssi-json-ld.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
iref.workspace = true
multibase.workspace = true
base64.workspace = true
serde_json.workspace = true
rdf-types.workspace = true
xsd-types.workspace = true
log.workspace = true
reqwest = "0.12.3"
parking_lot = "0.12.1"
flate2 = "1.0.28"

[dev-dependencies]
ssi-jws = { workspace = true, features = ["secp256r1"] }
ssi-dids.workspace = true
ssi-data-integrity = { workspace = true, features = ["w3c"] }
tokio = { version = "1.0", features = ["macros", "rt"] }
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
hyper = "1.2.0"
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
rand.workspace = true
